# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 75bfa64719016d3dc2c84bebd4b01cf0d826677c434636397e07b687599e010a0639b30d0c563b73cc094aabcf58625c0d6c6eb1a5c0b75573994cfaab5deabb

test:
  secret_key_base: 7414af5cca9739f29f4434cbb9c5c73d7fcf2252426e4a20411f30ef46dacf31be0d58e2f392419448db0344a0a29eb004c1c6efa5c57a8b262e08b9d94fbf2f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
